name: 'Docker Action Recipes'
description: 'Greet Someone'
branding:
  icon: bell
  color: green
author: 'Mensur Khalid'

inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"

outputs:
  answer:
    description: 'The answer to everything(always 42)'
  name:
    description: 'The maintainers name'

runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{inputs.who-to-greet}}
